### ISSUE TITLE
Private ?

### ISSUE THREAD

**Issue by colindaven** [tcooper/openxdmod_docker#1]
Hi, I'm interested in trialling xdmod on premises - preferably as a docker container. Is this repo going to stay private, or are you intending to make it accessible ?

Thanks,
Colin

**Comment by tcooper** [comment]
@colindaven ... there is nothing in this repo except for the README. It was created when we were working on dockerizing OpenXDMoD prior to the v8 release. Since then it appears the Buffalo team has already dockerized the application and is providing a public docker repository you can pull a container from. Have a look at the real XDMoD repository at... [https://github.com/ubccr/xdmod](https://github.com/ubccr/xdmod).
